import type { CommandCenterData } from "./types";

export const commandCenterData: CommandCenterData = {
  title: "Codex Metrics — Operator Console",
  subtitle:
    "Token burn, model mix, rolling limits, session health, and estimated spend in one operator-grade dashboard.",
  refreshStatus: "Updated just now",
  navItems: [],
  sideNote:
    "Data model: Codex JSONL session events plus OpenAI cost and usage APIs where available. Limit windows come from local Codex rate-limit events.",
  filters: [
    { label: "Live session", live: true },
    { label: "Last 7 days" },
    { label: "Local + API" },
  ],
  metrics: [
    {
      label: "Total tokens",
      source: "local",
      value: "12.8M",
      delta: "+18.4% vs prior week",
    },
    {
      label: "Estimated cost",
      source: "price map",
      value: "$41.72",
      delta: "Cached input saved $22.10",
    },
    {
      label: "Avg latency",
      source: "derived",
      value: "12.4s",
      delta: "p95 31.8s",
    },
    {
      label: "Success rate",
      source: "derived",
      value: "97.6%",
      delta: "11 failed tool exits",
    },
    {
      label: "Throughput",
      source: "derived",
      value: "1.9k/min",
      delta: "Output tokens per minute",
    },
  ],
  burnBars: [
    { day: "Mon", height: 46, totalTokens: 1_380_000, tone: "input" },
    { day: "Tue", height: 63, totalTokens: 1_890_000, tone: "input" },
    { day: "Wed", height: 31, totalTokens: 930_000, tone: "output" },
    { day: "Thu", height: 82, totalTokens: 2_460_000, tone: "input" },
    { day: "Fri", height: 58, totalTokens: 1_740_000, tone: "input" },
    { day: "Sat", height: 37, totalTokens: 1_110_000, tone: "output" },
    { day: "Sun", height: 71, totalTokens: 2_130_000, tone: "input" },
  ],
  limitWindows: [
    {
      title: "5 hour usage",
      copy: "Primary window resets at 23:38. Current model: gpt-5.5 high.",
      progress: 63,
      status: "watch",
    },
    {
      title: "Weekly usage",
      copy: "Secondary window resets Monday morning. Trend is below weekly pace.",
      progress: 28,
      status: "ok",
    },
  ],
  sessions: [
    {
      name: "22:37 codex-metrics",
      model: "gpt-5.5 high",
      tokens: "592.5k",
      cost: "$1.94",
      status: "live",
    },
    {
      name: "20:52 portfolio-work",
      model: "gpt-5.4 medium",
      tokens: "1.8M",
      cost: "$5.80",
      status: "ok",
    },
    {
      name: "11:06 app-debug",
      model: "gpt-5.4 mini",
      tokens: "438k",
      cost: "$0.41",
      status: "retry",
    },
  ],
  modelUsage: [
    { model: "gpt-5.5 high", share: 61, tone: "green" },
    { model: "gpt-5.5 medium", share: 22, tone: "orange" },
    { model: "gpt-5.4 mini", share: 12, tone: "blue" },
    { model: "other", share: 5, tone: "red" },
  ],
  kpis: [
    {
      label: "Success Rate",
      value: "91%",
      color: "success",
      delta: "+2%",
      deltaDirection: "up",
      sparkline: [85, 87, 88, 89, 90, 91, 91],
    },
    {
      label: "Latency p95",
      value: "2.6",
      unit: "s",
      color: "warning",
      delta: "-0.3s",
      deltaDirection: "down",
      sparkline: [8, 7, 6, 5, 4, 3, 3],
    },
    {
      label: "Throughput",
      value: "33.5",
      unit: "k",
      color: "accent",
      delta: "+5%",
      deltaDirection: "up",
      sparkline: [28, 30, 31, 32, 33, 33, 34],
    },
    {
      label: "Active Sessions",
      value: "3",
      color: "default",
      delta: "stable",
      deltaDirection: "neutral",
      sparkline: [2, 2, 3, 3, 3, 3, 3],
    },
    {
      label: "Daily Burn / 95% limit",
      value: "313.3",
      unit: "M",
      color: "info",
      delta: "",
      deltaDirection: "neutral",
      sparkline: [15, 28, 67, 180, 55, 210, 12],
    },
    {
      label: "Rate Limit — weekly / 5h",
      value: "8%",
      color: "success",
      delta: " / 0%",
      deltaDirection: "neutral",
      sparkline: [2, 2, 4, 4, 4, 2, 2],
    },
    {
      label: "Current RPM",
      value: "114",
      color: "accent",
      delta: "",
      deltaDirection: "neutral",
      sparkline: [80, 90, 100, 110, 114, 112, 115],
    },
    {
      label: "Error Rate (5m)",
      value: "2.1%",
      color: "warning",
      delta: "-0.5%",
      deltaDirection: "down",
      sparkline: [5, 4, 4, 3, 3, 2, 2],
    },
  ],
  tokenBurn: {
    composition: [
      { label: "input", value: 312_100_000, color: "--accent" },
      { label: "cached", value: 296_600_000, color: "--success" },
      { label: "output", value: 1_100_000, color: "--info" },
      { label: "reasoning", value: 297_000, color: "--warning" },
    ],
    areaChart: {
      input: [7, 6, 5, 4, 3, 2, 1, 0.5, 0.3, 0.1],
      cached: [6, 5.5, 5, 4.5, 4, 3.5, 3, 2.5, 2, 1.5],
    },
    dailyBurn: [
      { day: "Mon", tokens: 15_000_000 },
      { day: "Tue", tokens: 28_000_000 },
      { day: "Wed", tokens: 67_000_000 },
      { day: "Thu", tokens: 180_000_000 },
      { day: "Fri", tokens: 55_000_000 },
      { day: "Sat", tokens: 210_000_000 },
      { day: "Sun", tokens: 12_000_000 },
    ],
    modelMix: [{ model: "openai", share: 100 }],
  },
  rateLimits: {
    rows: [
      {
        window: "5h primary",
        used: "0%",
        remaining: "100%",
        countdown: "resets 13:04 (2h 57m)",
        status: "ok",
      },
      {
        window: "1w secondary",
        used: "8%",
        remaining: "92%",
        countdown: "resets May 08 20:38 (5d 10h)",
        status: "ok",
      },
    ],
    burnRate: [80, 82, 85, 88, 90, 92, 95, 100, 105, 110, 112, 114],
    projection: "Safe — no exhaustion risk",
    safeBudget: 92,
  },
  sessionStream: {
    rows: [
      { id: "rooted-on-rhea", repo: "/projects/", model: "openai", turns: 12, tokens: "19.3M", latency: "10.2s", success: "retry", age: "2d" },
      { id: "codex-metrics", repo: "/tools/", model: "openai", turns: 8, tokens: "20M", latency: "8.1s", success: "retry", age: "1d" },
      { id: "codex", repo: "/cli/", model: "openai", turns: 5, tokens: "1.7M", latency: "12.4s", success: "retry", age: "3d" },
      { id: "rooted-on-rhea", repo: "/projects/", model: "openai", turns: 3, tokens: "734.2k", latency: "4.2s", success: "retry", age: "4h" },
      { id: "codex-metrics", repo: "/tools/", model: "openai", turns: 15, tokens: "256.5k", latency: "15.1s", success: "unknown", age: "5h" },
      { id: "codex-docs", repo: "/docs/", model: "openai", turns: 6, tokens: "1.2M", latency: "6.8s", success: "ok", age: "3h" },
      { id: "codex-infra", repo: "/infra/", model: "openai", turns: 4, tokens: "890k", latency: "5.5s", success: "ok", age: "1h" },
      { id: "rooted-on-rhea", repo: "/projects/", model: "openai", turns: 2, tokens: "420k", latency: "3.1s", success: "ok", age: "45m" },
      { id: "codex-api", repo: "/api/", model: "openai", turns: 7, tokens: "2.1M", latency: "9.4s", success: "ok", age: "12h" },
      { id: "codex-core", repo: "/core/", model: "openai", turns: 1, tokens: "150k", latency: "2.2s", success: "ok", age: "15m" },
    ],
    turnHistogram: [
      { label: "1-3", value: 3 },
      { label: "4-6", value: 2 },
      { label: "7-10", value: 1.5 },
      { label: "11-15", value: 2.5 },
      { label: "16+", value: 1 },
    ],
    scatter: [
      { x: 0.1, y: 0.3 },
      { x: 0.2, y: 0.35 },
      { x: 0.3, y: 0.5 },
      { x: 0.4, y: 0.25 },
      { x: 0.5, y: 0.4 },
      { x: 0.6, y: 0.3 },
      { x: 0.7, y: 0.2 },
      { x: 0.8, y: 0.45 },
    ],
    longest: [
      { name: "codex", age: "3d" },
      { name: "rooted-on-rhea", age: "2d" },
      { name: "codex-metrics", age: "1d" },
      { name: "codex-api", age: "12h" },
      { name: "rooted-on-rhea", age: "4h" },
    ],
    biggest: [
      { name: "codex-metrics", tokens: "20M" },
      { name: "rooted-on-rhea", tokens: "19.3M" },
      { name: "codex", tokens: "1.7M" },
      { name: "codex-api", tokens: "2.1M" },
      { name: "codex-docs", tokens: "1.2M" },
    ],
  },
  cache: {
    hitRatio: 95,
    tokensSaved: "296.6M",
    savings: "$89.00",
    uncachedTrend: [
      2_000_000, 1_900_000, 1_800_000, 1_700_000, 1_600_000, 1_500_000, 1_400_000,
      1_300_000, 1_200_000, 1_100_000, 1_000_000,
    ],
    byModel: [{ model: "openai", ratio: 95 }],
  },
  context: {
    avgUsage: 34,
    maxUsage: 87,
    thresholds: [
      { label: "50%", count: 12, width: 48 },
      { label: "75%", count: 4, width: 16 },
      { label: "90%", count: 1, width: 4 },
    ],
    candidates: [
      { session: "rooted-on-rhea", current: 87, turnsLeft: "~2 turns" },
      { session: "codex", current: 82, turnsLeft: "~3 turns" },
    ],
    growth: [5, 8, 12, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
  },
  tools: {
    calls: [
      { tool: "exec_command", count: 45 },
      { tool: "web_search", count: 12 },
      { tool: "function_call", count: 8 },
    ],
    failed: [
      { tool: "exec_command", command: "git push", session: "rooted-on-rhea", error: "exit 1", time: "10:04" },
      { tool: "exec_command", command: "npm test", session: "codex-metrics", error: "exit 1", time: "09:52" },
    ],
    failureRate: [
      { tool: "exec_command", rate: 4.4 },
      { tool: "web_search", rate: 0 },
      { tool: "function_call", rate: 0 },
    ],
    slowest: [
      { tool: "exec_command", command: "npm test", latency: "15.1s", count: 3 },
      { tool: "web_search", command: "search", latency: "8.2s", count: 12 },
    ],
    retryProne: [
      { session: "rooted-on-rhea", retries: 4 },
      { session: "codex-metrics", retries: 3 },
    ],
  },
  repos: {
    distribution: [
      { name: "/projects/", tokens: 220_000_000 },
      { name: "/tools/", tokens: 20_300_000 },
      { name: "/cli/", tokens: 1_700_000 },
      { name: "/other/", tokens: 256_000 },
    ],
    failures: [
      { name: "/projects/", count: 11, width: 55 },
      { name: "/tools/", count: 6, width: 30 },
      { name: "/cli/", count: 3, width: 15 },
    ],
    latency: [
      { name: "/projects/", tokens: 220_000_000, failures: 11, avgLatency: "8.5s", p95Latency: "15.1s", count: 45 },
      { name: "/tools/", tokens: 20_300_000, failures: 6, avgLatency: "9.2s", p95Latency: "12.4s", count: 23 },
      { name: "/cli/", tokens: 1_700_000, failures: 3, avgLatency: "10.1s", p95Latency: "14.2s", count: 12 },
    ],
    mostExpensiveRepo: { name: "/projects/", tokens: "220M" },
    mostExpensiveSession: { name: "rooted-on-rhea", tokens: "19.3M" },
  },
  billing: {
    byDay: [
      { day: "Apr 20", amount: 5 },
      { day: "Apr 21", amount: 7 },
      { day: "Apr 22", amount: 10 },
      { day: "Apr 23", amount: 8 },
      { day: "Apr 24", amount: 12 },
      { day: "Apr 25", amount: 15 },
      { day: "Apr 26", amount: 18 },
      { day: "Apr 27", amount: 22 },
      { day: "Apr 28", amount: 20 },
      { day: "Apr 29", amount: 25 },
      { day: "Apr 30", amount: 30 },
      { day: "May 01", amount: 28 },
      { day: "May 02", amount: 35 },
      { day: "May 03", amount: 38 },
    ],
    breakdown: [
      { label: "/projects/", value: 70, cost: "$8.75" },
      { label: "/tools/", value: 20, cost: "$2.50" },
      { label: "/cli/", value: 10, cost: "$1.25" },
    ],
    completions: [
      { model: "gpt-4", project: "default", user: "suwan", key: "sk-xxx", tier: "standard", tokens: "312M", cost: "$12.50" },
    ],
    totalRequests: 3327,
    batchShare: 0,
  },
  products: [
    { name: "Embeddings", metric: "0", unit: "", cost: "$0.00", sparkline: [0, 0, 0, 0, 0, 0, 0] },
    { name: "Images", metric: "0", unit: "", cost: "$0.00", sparkline: [0, 0, 0, 0, 0, 0, 0] },
    { name: "Audio Transcription", metric: "0", unit: "s", cost: "$0.00", sparkline: [0, 0, 0, 0, 0, 0, 0] },
    { name: "Audio Speech", metric: "0", unit: "chars", cost: "$0.00", sparkline: [0, 0, 0, 0, 0, 0, 0] },
    { name: "Code Interpreter", metric: "0", unit: "", cost: "$0.00", sparkline: [0, 0, 0, 0, 0, 0, 0] },
    { name: "Vector Stores", metric: "0", unit: "B", cost: "$0.00", sparkline: [0, 0, 0, 0, 0, 0, 0] },
    { name: "Moderation", metric: "0", unit: "", cost: "$0.00", sparkline: [0, 0, 0, 0, 0, 0, 0] },
  ],
};
